name: Run eslint & prettier linter
on:
  workflow_dispatch:
  push:
    branches-ignore:
      - release
  pull_request:
    branches-ignore:
      - release
jobs:
  run-eslint:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npx pnpm i
      - run: npx pnpm lint
  